{{- if .Values.database.postgresql.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "attstore.postgresql.fullname" . }}
  labels:
    {{- include "attstore.postgresql.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.database.postgresql.username | quote }}
  POSTGRES_PASSWORD: {{ include "attstore.postgresql.password" . | quote }}
  POSTGRES_DB: {{ .Values.database.postgresql.database | quote }}
{{- end }}
