{{- if .Values.minio.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "attstore.minio.fullname" . }}
  labels:
    {{- include "attstore.minio.labels" . | nindent 4 }}
type: Opaque
stringData:
  MINIO_ROOT_USER: {{ .Values.minio.rootUser | quote }}
  MINIO_ROOT_PASSWORD: {{ include "attstore.minio.password" . | quote }}
{{- end }}
